version: "3.4"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/www/:/data/www/:rw
      - ./nginx/:/etc/nginx/:rw
      - ./log/nginx/:/data/log/nginx/:rw
    restart: always
    networks:
      - net-golang

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data/:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    networks:
      - net-mysql

  redis:
    image: redis:4.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net-redis

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - net-jaeger

  etcd:
    image: quay.io/coreos/etcd
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
    environment:
      - ETCDCTL_API=3
    networks:
      - net-etcd

  golang:
    build: ./golang
    expose:
      - "8090"
    volumes:
      - ./log/golang/:/data/log/golang/:rw
    restart: always
    depends_on:
      - "jaeger"
      - "mysql"
      - "redis"
      - "etcd"
    networks:
      - net-golang
      - net-mysql
      - net-redis
      - net-jaeger
      - net-etcd


networks:
  net-golang:
  net-mysql:
  net-redis:
  net-jaeger:
  net-etcd:

